services:
  mushroomd:
    build: .
    volumes:
      - data:/data
  webproxy:
    build: ./client
    environment:
      MUSHROOMD_HOST: "mushroomd"
      MUSHROOMD_PORT: "1337"
    ports:
      - "1338:1338"
  client:
    image: nginx:1.25.5
    ports:
      - "8000:80"
    volumes:
      - "${PWD}/client/static/index.html:/usr/share/nginx/html/index.html"

volumes:
  data:
